[package]
name = "comp_rects"
version = "0.1.0"
authors = ["CaesarJeries <caesar.dakwar@outlook.co.il>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
